language: perl
matrix:
  include:
    - perl: "5.10"
      secure: "TDCDrRoRqd7a/6aIKJnzTgewOqnABjU2gBPGetW0imvK47SIvkP30haKgw3B\ncwftLPVx/vWhW7MIDzC8Grlh7CbpvVYTx4AQ0ozPWRm6B4gey1lGMFcpnsj3\nnvLuLWycKKK1aB2e9HfL22ZHBzXsMqj1G6iUNUP4Fx0lNjr/bQQ="
    - perl: "5.12"
      secure: "A1Xx/oZoxIkpgdfIyIOGCl5IlLJkKXtArFLHCtWnsGzqcrgeRIC72k/1uQ+P\nBEmg9X2ohC4/VhrIHA6Pn33/Kk1fLF3mr1enucQVDtQBbRFakGCtzP7pYrEr\n1hrzSEDNySe0vrceingR7TmVwjd4rYd9mUv7DDDtbt8eANl7UGg="
    - perl: "5.14"
      secure: "KYCwN139LUiLsgBOmoXyOsEPYTKSNnxwD+7lfXaM7AgCsLBk5H86sq5Y6AWr\neT9rwBXLpM50OTEUQfmDQRkJUwzL1CKMNdtAFbDehIWyX+QYLLsgwP6yiM3A\n2nV5UKNwjH0c0EFnWgy80qootvtQIpJ1r9PQJ4lqGj61WItRfjw="
    - perl: "5.16"
      secure: "Q4kihl9gGN9edekbhuUraNnO/3KDhr66Wsejr7/xeyBTvseMm+8I1iHQlb64\nLtqu/R4GeSu93tGc5uFqMzXZmOuhAiWpfAXSlY+uZJszXdba5Jvpyr5jaTpd\nhd4HEYdRj1M2SpmwBvaWKryjvY1NnpAupf9Wi3US8hGMI9WsV1w="
