---
abstract: "A Perl wrapper for the Campaign Monitor API.\r"
author:
  - jeffery@astraaustralis.com.au
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.02'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Net::CampaignMonitor
name: Net-CampaignMonitor
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 1.11
  JSON: 2.27
  LWP::UserAgent: 5.835
  Params::Util: 1.01
  MIME::Base64: 3.13
  REST::Client: 171
  XML::Simple: 2.18
  perl: 5.8.5
resources:
  license: http://dev.perl.org/licenses/
  bugtracker: https://github.com/campaignmonitor/createsend-perl/issues
  homepage: http://campaignmonitor.github.com/createsend-perl/
  repository: https://github.com/campaignmonitor/createsend-perl.git
version: v2.2.0
